// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FunctionCalls string
	Functions     string
	RelUserWallet string
	Users         string
	Wallets       string
}{
	FunctionCalls: "function_calls",
	Functions:     "functions",
	RelUserWallet: "rel_user_wallet",
	Users:         "users",
	Wallets:       "wallets",
}
